# Default values for multi-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  tag: 0.23.0
  pullPolicy: IfNotPresent

identifier: "placeholder"
certificateARN: ""
